### PR TITLE
botocore is missing in requirements of python-fullstack example

### PR DESCRIPTION
**Pull request by rohit-metrum-ai**
botocore is missing in requirements of python-fullstack example added latest version of botocore==1.35.15 in requirements

### CODE REVIEW

**Comment by logan-markewich** [comment]
@Rohith-Scalers which package is requiring this? Do you have an example of a traceback?

I was able to run this just fine with the existing requirements 👀

**Comment by mmezaj** [comment]
@logan-markewich i run into the same issue as @Rohith-Scalers. The issues happens in the build of the frontend/dockerfile. 
Docker_Desktop_vtOJQk2QIA

**Comment by nerdai** [comment]
This was my bad @logan-markewich. When testing the `AWSMessageQueue` with our collaborator in that PR, I had to publish a pre-release `v0.1.2ax`. Looks like pip is trying to install this pre release unfortunately.

**Comment by logan-markewich** [comment]
@nerdai can we make one more release to patch the dependencies / imports for `llama_deploy` properly?

**Comment by nerdai** [comment]
Yeah good call. Will try that now.

**Comment by nerdai** [comment]
> @nerdai can we make one more release to patch the dependencies / imports for `llama_deploy` properly?

Alright I published a new patch/pre-release that delays the imports of artifacts from optional deps (namely `botocore`). Everything should work as before now.

**Comment by logan-markewich** [comment]
@Rohith-Scalers @mmezaj your issue should be resolved now

**Pull request closed without merging**
