### PR TITLE
some unit test cases added

### PR DESCRIPTION
**Pull request by latentloop07**
I will continue adding more, its just the first PR.

### CODE REVIEW

**Comment by nerdai** [comment]
Thanks @atharvapatiil :) ... looks like a couple of our checks are failing (lint and testing). Can you kindly try to address them?

**Comment by latentloop07** [comment]
Sure @nerdai

**Comment by latentloop07** [comment]
@nerdai Could you please approve the trigger for workflows ?

**Comment by latentloop07** [comment]
@nerdai  please re-trigger workflows once again. lint error resolved.

**Comment by latentloop07** [comment]
All tests are passed.
@nerdai  please review and approve the PR for merge.

**Review by nerdai — APPROVED** [review]
Thanks @atharvapatiil for the added unit tests!

Ooc: are you able to provide the coverage reports before and after these tests?

**Comment by latentloop07** [comment]
@nerdai  from next time I will add coverage report as well. But I guess some ~3-4 % must have increased this time. 
Please it merge as well. It is not merging automatically I guess.

**Comment by nerdai** [comment]
> @nerdai from next time I will add coverage report as well. But I guess some ~3-4 % must have increased this time. Please it merge as well. It is not merging automatically I guess.

sgtm - thanks! I don't think I had clicked on "enable automatic merge". Merging now.

**Pull request merged**
