### PR TITLE
AWS SQS MessageQueue Integration

### PR DESCRIPTION
**Pull request by nerdai**
This originally came from #158 but @nerdai made a silly error somehow and merged it into main prematurely. It has since been reverted from the main repo.

This is the PR re-opened.

- Adds SQSMessageQueue
- Uses AWS SNS and SQS

(Cc @MartinRistov)

### CODE REVIEW

**Comment by nerdai** [comment]
@MartinRistov sorry for making a mess of things by accidentally merging into `main` and having to revert. I have no idea how that even happened tbh with our branch protection rules.

Anyways, this PR is re-opened and is coming from your `fork`. This time however I have created the branch `aws-sqs-integration` in your branch. Please do make changes on there moving forward, and they'll get reflected here.

I think we have the following things left to do:

- implement `cleanup_local()`: I think you had it before, but it needs to be updated to sns/sqs logic we have now. Maybe we should delete topic from sns and delete all queues from sqs.
- add README.md in `examples/awssqs` folder to explain how to use this message queue and set up AWS creds

**Comment by MartinRistov** [comment]
@nerdai Combed through the code and did a first-pass clean-up.  Few thoughts that came to mind:
1. We are creating both SNS topics and SQS queues for each service, but the class name is `SQSMessageQueue`. Not a big deal, but something to think about for better clarity.
2. `message_group_id` - having this in the class constructor is a great call. I added some comments in the examples to call out that we are enforcing strict message ordering across different agents. May be a stretch goal, but if there is a use case for concurrent agent runs, may be good to spin up another example to demonstrate it, just for the sake of contrasting the different message ordering capabilities.
3. For this to run at scale, each of the services would need to be individually containerized, especially the horizontally-scalable ones. I see you've already done some great work with `examples/docker-kubernetes/multi-agent-app/Dockerfile` and `examples/docker-kubernetes/docker-compose.yml`, but I haven't yet played with it. Since we're building a AWS-native solution here - I think it'd be valuable to get this running in ECS, then "template-tize" it so others can spin this up in true serverless fashion.

I'll work on the readme and cleanup next, and below are some other smaller enhancements I was also considering adding:
- Implement exponential backoff with retries for AWS API calls to handle transient errors gracefully
- Check if the topic/queue already exists before creating

Curious to hear your thoughts!

**Comment by nerdai** [comment]
@MartinRistov That list sounds fantastic! We do have some examples where we spin out each agent/human service as its own service in its own pod. In that example, they all use the same Docker image, but you can change the command for the container in order to spin up the desired service. In that K8s [example](https://github.com/run-llama/llama-agents/tree/main/examples/rabbitmq#launching-with-kubernetes) you can change replica set for any of the agent services to greater than 1, and have multiple copies of that service listening/consuming its dedicated messages (i.e tasks)! It'd be great to have an example that leverages EKS!

In terms of naming, should we change it to `AWSMessageQueue` instead?

**Comment by nerdai** [comment]
hey hey @MartinRistov! Just checking in on how we're doing here? Let me know if you're stuck with anything or if there is something that I can support you with :)

**Comment by MartinRistov** [comment]
@nerdai I'll get the rest of the to-dos ironed out this week, but a few things:
- renamed class to your suggestion, I like it.
- `cleanup_local` now cleans up all created topics and queues. I assume by the name, this is somehow invoked only for local runs. Am I correct to assume this is only the case for workflows spun up with`LocalLauncher` ?
- is there a use case for having agents (assuming they are part of a single agentic system) to be instantiated with different `AWSMessageQueue`s, and unique `message_group_id`s by extension? I understand that with SNS topics, messages with the same `MessageGroupId` are guaranteed to be processed in the order they are sent, but was curious why (or if) we would leave this value configurable in the class constructor at all. Maybe we remove it?

**Comment by nerdai** [comment]
Thanks for moving this forward, @MartinRistov! Glad you like the rename suggestion as well. Re your last two points:

- thanks for implementing `cleanup_local`, and yes, you're right its basically only used with `LocalLauncher`...
- you raise a good point... i don't think we need this to be configurable :)

**Comment by MartinRistov** [comment]
@nerdai - Just pushed another round of updates.

I also created a new local script `local_launcher_router_component_single_bedrock.py` with a Bedrock-hosted LLM in the loop, for a more AWS-native experience - but came across a minor issue. Details below, along with instructions if you wanted to try it yourself:

1. Attach `AmazonBedrockFullAccess` policy to the IAM role we've been using. This access is likely too much, but I'll narrow it down to just the single policy for inferencing once we publish this live (I think `bedrock::InvokeModel` should suffice in theory - but need to confirm)
2. Note down your current `aws` cli profile with `aws configure list-profiles`. I only got one on this machine, so was `default` in my case. Update it [in the test script](https://github.com/run-llama/llama-agents/pull/161/commits/cc8da6558e9e0c66b40fc8a0ed6b1c766904ec39#diff-407ad4d1e1437213ba834e775b403a08ef122ec5a90ce507ae7588a640b4b082R16) if needed.
3. In the AWS console, within the Bedrock service, request access to a model you'd like to use.
4. After approval, copy the model's ID - I used Claude 3 Opus in my case. [Update this ID in your instance of the new script](https://github.com/run-llama/llama-agents/pull/161/commits/cc8da6558e9e0c66b40fc8a0ed6b1c766904ec39#diff-407ad4d1e1437213ba834e775b403a08ef122ec5a90ce507ae7588a640b4b082R17).
5. Launch the new test script, everything should work as before. This issue I saw here is with the `selector` of the `RouterComponent` [here](https://github.com/run-llama/llama-agents/pull/161/commits/cc8da6558e9e0c66b40fc8a0ed6b1c766904ec39#diff-407ad4d1e1437213ba834e775b403a08ef122ec5a90ce507ae7588a640b4b082R57). Did not dig into this too much, but tl;dr I was not able to use my newly configured Bedrock model, instead had to use `OpenAI()`. Not sure how big of a deal this is, but bringing it to your attention regardless. 

What's left on my to-do list:
- readme
- run current setup as multiple containerized workloads on ECS (not EKS, as ideally we should deploy and run in as serverless fashion as possible). The best tangible output of this *could* be a new AWS CDK "starter pack" running on Fargate. [Here is a random example](https://github.com/aws-samples/serverless-patterns/tree/main/fargate-sns-sqs-cdk) from ServerlessLand.com, but it's basically doing a lot of heavy-lifting under the hood - taking care of pushing to ECR, spinning up an ECS cluster with networking resources, etc. It may be a stretch goal, but I see it as a great starting point for anyone looking to start building a production-grade environment on AWS.
- blog (+ @jerryjliu fyi - if you had any thoughts on the messaging)

Give me a shout if you've got something else in mind. Appreciate you!

**Comment by nerdai** [comment]
amazing stuff @MartinRistov! I'll try it out for myself at some point today (probably a bit later on) with your instructions. I'll share any comments/questions that come up after doing so. Cheers!

**Comment by MartinRistov** [comment]
Dropping this here so I don't forget (thanks @nerdai )
> we do have some orchestration changes coming to llama-agents, that wont' change the need for message queues, but will change how we build our examples... specifically we won't have pipeline or agent orchestrator anymore

Holding off on further updates until workflows and llama-agents get consolidated

**Comment by nerdai** [comment]
Thanks @MartinRistov. We shall pick this back up soon!

**Comment by MartinRistov** [comment]
@nerdai just a friendly follow-up to see how far you guys have gotten with the consolidation effort. would love to help drive this forward - cheers

**Comment by logan-markewich** [comment]
@MartinRistov its actually very close -- hoping to merge this branch this week
https://github.com/run-llama/llama-agents/tree/v0.1.0

**Comment by MartinRistov** [comment]
Great work guys!

Update from my end:
- Created a new branch off my original fork since I wanted to port over the existing changes on a clean slate.
- Pushed the changes on it, [here's that commit](https://github.com/run-llama/llama_deploy/commit/b85973803d5fc479e7d1492398fbd2d3a752a617). If there's a better way to approach this, feel free to clean up (new PR?)
- Everything _should_ work, but am coming across the following error with the `control-plane` serivce/container crashing:
```
control_plane-1        |   File "/app/multi_workflows_app/deployment/core.py", line 10, in <module>
control_plane-1        |     from llama_deploy.message_queues.aws import AWSMessageQueueConfig
control_plane-1        | ModuleNotFoundError: No module named 'llama_deploy.message_queues.aws'
Gracefully stopping... (press Ctrl+C again to force)
dependency failed to start: container message-queue-integrations-control_plane-1 exited (1)
```
- I made sure I init everything properly, so I suspect it's likely something to do with the way my local changes are ported over to the container image. @nerdai mind taking a quick look, if you get a moment?

PS. Other than the OpenAI API key, this setup expects your AWS creds in `.env.aws` - I added `examples/message-queue-integrations/aws/docker/template.env.aws` as a placeholder so it follows the same standards as the other MQ implementations.

**Comment by nerdai** [comment]
Thanks @MartinRistov!! I'll be looking at this later in the evening today 🙏

**Comment by MartinRistov** [comment]
Appreciate you @nerdai - no rush on my end! Took another stab, but still no luck. I did revise some additional things in [this new commit](https://github.com/MartinRistov/llama-agents/commit/6abff7541127ebd3b11eb347c891c4697c113d28) - but I'll pause here :)

**Comment by nerdai** [comment]
On it now @MartinRistov -- thanks!

**Comment by nerdai** [comment]
@MartinRistov I created a new PR #246 for this as it seems the most clean thing to do given our updates to llama-deploy.

Let's continue our discussion there.

**Pull request closed without merging**
